In [3]:
data_dir = "./covid19-global-forecasting-week-1/"

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime
import tensorflow as tf
import math

# Read dataset

In [4]:
train_df_raw = pd.read_csv(data_dir+"train.csv")
test_df_raw = pd.read_csv(data_dir+"test.csv")
all_df = train_df_raw
test_df = test_df_raw

In [5]:
# paramerers
maxlen = 30
hidden_number = 32
input_number = 5
output_number = 2
batch_size = 32
epochs = 50
lr = 0.001

# Preprocessing

I Normalize the numeric values and make date column to the numeric values.   
The final day of the training dataset is used as the validation data.

In [6]:
def map_datetime(date):
    return (date - datetime.datetime.strptime('2020-01-22', "%Y-%m-%d")).days

def to_datetime(date):
    return datetime.datetime.strptime(date, "%Y-%m-%d")

In [7]:
test_df = test_df.fillna({"Province/State": "NAN"})
all_df = train_df.fillna({"Province/State": "NAN"})

all_df["ConfirmedCases"] = (all_df["ConfirmedCases"] + 1).map(math.log10)
cases_max = all_df["ConfirmedCases"].max()
fatal_max = all_df["Fatalities"].max()

all_df["Lat"] = all_df["Lat"]/180.
all_df["Long"] = all_df["Long"]/180.
all_df["ConfirmedCases"] = all_df["ConfirmedCases"] / cases_max
all_df["Fatalities"] = all_df["Fatalities"] / fatal_max

all_df["Date"] = all_df["Date"].map(to_datetime)
all_df["Date_num"] = all_df["Date"].map(map_datetime)
date_max = all_df["Date_num"].max()
all_df["Date_num"] = all_df["Date_num"] / date_max

date_unit = all_df.iloc[1]["Date_num"] - all_df.iloc[0]["Date_num"]

val_df = all_df[all_df["Date"] > (all_df["Date"].max() - datetime.timedelta(days=(maxlen+1)))]
train_df = all_df.drop(all_df[all_df["Date_num"] == all_df["Date_num"].max()].index)

test dataframe is also preprocessed

In [8]:
test_df["Lat"] = test_df["Lat"]/180.
test_df["Long"] = test_df["Long"]/180.
test_df["Date"] = test_df["Date"].map(to_datetime)
test_df["Date_num"] = test_df["Date"].map(map_datetime)
test_df["Date_num"] = test_df["Date_num"] / date_max

# Preprocessing for LSTM

Reshape the dataset to sequences.  

Input data components are Latitude, Longnitude, Date, ConfirmedCases, Fatalities.  
Output data components are ConfirmedCases, Fatalities.  


In [9]:
def make_sequences(train_df):
    inputs = []
    targets = []
    for i in range(len(train_df) - maxlen - 1):
        if train_df.iloc[i]["Lat"] == train_df.iloc[i+maxlen]["Lat"] and \
           train_df.iloc[i]["Long"] == train_df.iloc[i+maxlen]["Long"]:
            inputs.append(np.array(train_df.iloc[i:i+maxlen][["Date_num", "Lat", "Long", "ConfirmedCases", "Fatalities"]]).tolist())
            targets.append(np.array(train_df.iloc[i+maxlen][["ConfirmedCases", "Fatalities"]]).tolist())
    return inputs, targets

In [10]:
train_inputs, train_targets = make_sequences(train_df)
val_inputs, val_targets = make_sequences(val_df)

# Make LSTM model
In this section, I made two layered simple LSTM model.

In [11]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.LSTM(hidden_number, batch_input_shape=[None, maxlen, input_number], return_sequences=True))
model.add(tf.keras.layers.LSTM(hidden_number))
model.add(tf.keras.layers.Dense(output_number, activation="sigmoid"))

optimizer = tf.keras.optimizers.Adam(lr=lr)
model.compile(loss="mean_squared_error", optimizer=optimizer)

In [12]:
model.load_weights("./tmp/param.hdf5")

In [ ]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', mode='auto', patience=5)
history = model.fit(train_inputs, train_targets,
                    batch_size=batch_size,
                      epochs=epochs,
                      validation_data=(val_inputs, val_targets),
                      callbacks = [early_stopping]
                      )

# Prediction phase

In [13]:

all_df

Predict 43 days recursively by many-to-one LSTM model.  
The prediction step is one step. So, the prediction is recursively continued to predict 43 days cases.

In [70]:
results = []
for idx in test_df.groupby(["Province/State", "Country/Region"]).count().index:
    test_df_on_idx = test_df[(test_df["Province/State"] == idx[0]) &
                             (test_df["Country/Region"] == idx[1])]
    train_df_on_idx = train_df[(all_df["Country/Region"] == idx[1]) &
                               (all_df["Province/State"] == idx[0])]
    inputs = np.array(train_df_on_idx[["Date_num", "Lat", "Long", "ConfirmedCases", "Fatalities"]])[-maxlen:]
    inputs = inputs.reshape(maxlen, input_number)
    for day in range(43):
        if int(1000000000*(datetime.timedelta(days=day) + test_df_on_idx["Date"].min()).timestamp()) in train_df_on_idx["Date"].values.tolist():
            result = np.array(train_df_on_idx[train_df_on_idx["Date"] == (datetime.timedelta(days=day) + test_df_on_idx["Date"].min())][["Date", "Lat", "Long", "ConfirmedCases", "Fatalities"]])[0, 3:]
        else:
            result = model.predict(np.array(inputs).reshape(1, maxlen, input_number)).reshape(-1)
            inputs = np.concatenate((inputs[1:], np.append(inputs[-1, :3], result).reshape(1, input_number)), axis=0)
        results.append([10**(result[0]*cases_max), result[1]*fatal_max])

find the day in teacher
[0.0 0.0]
find the day in teacher
[0.16106669895297376 0.0]
find the day in teacher
[0.17492377160560507 0.0]
find the day in teacher
[0.23057108561891348 0.0]
find the day in teacher
[0.30574395958841427 0.0]
find the day in teacher
[0.3316045745613166 0.0]
find the day in teacher
[0.3461014580022392 0.0]
find the day in teacher
[0.3927829342781318 0.0]
[[ 0.48275862  0.17954556 -0.48279056  0.          0.        ]
 [ 0.5         0.17954556 -0.48279056  0.          0.        ]
 [ 0.51724138  0.17954556 -0.48279056  0.          0.        ]
 [ 0.53448276  0.17954556 -0.48279056  0.          0.        ]
 [ 0.55172414  0.17954556 -0.48279056  0.          0.        ]
 [ 0.56896552  0.17954556 -0.48279056  0.          0.        ]
 [ 0.5862069   0.17954556 -0.48279056  0.          0.        ]
 [ 0.60344828  0.17954556 -0.48279056  0.          0.        ]
 [ 0.62068966  0.17954556 -0.48279056  0.          0.        ]
 [ 0.63793103  0.17954556 -0.48279056  0.          0

[0.00305647 0.00226174]
[[ 0.5862069   0.17954556 -0.48279056  0.          0.        ]
 [ 0.60344828  0.17954556 -0.48279056  0.          0.        ]
 [ 0.62068966  0.17954556 -0.48279056  0.          0.        ]
 [ 0.63793103  0.17954556 -0.48279056  0.          0.        ]
 [ 0.65517241  0.17954556 -0.48279056  0.          0.        ]
 [ 0.67241379  0.17954556 -0.48279056  0.          0.        ]
 [ 0.68965517  0.17954556 -0.48279056  0.          0.        ]
 [ 0.70689655  0.17954556 -0.48279056  0.          0.        ]
 [ 0.72413793  0.17954556 -0.48279056  0.          0.        ]
 [ 0.74137931  0.17954556 -0.48279056  0.          0.        ]
 [ 0.75862069  0.17954556 -0.48279056  0.          0.        ]
 [ 0.77586207  0.17954556 -0.48279056  0.          0.        ]
 [ 0.79310345  0.17954556 -0.48279056  0.          0.        ]
 [ 0.81034483  0.17954556 -0.48279056  0.          0.        ]
 [ 0.82758621  0.17954556 -0.48279056  0.          0.        ]
 [ 0.84482759  0.17954556 -0.48

[0.00305308 0.00225825]
[[ 0.67241379  0.17954556 -0.48279056  0.          0.        ]
 [ 0.68965517  0.17954556 -0.48279056  0.          0.        ]
 [ 0.70689655  0.17954556 -0.48279056  0.          0.        ]
 [ 0.72413793  0.17954556 -0.48279056  0.          0.        ]
 [ 0.74137931  0.17954556 -0.48279056  0.          0.        ]
 [ 0.75862069  0.17954556 -0.48279056  0.          0.        ]
 [ 0.77586207  0.17954556 -0.48279056  0.          0.        ]
 [ 0.79310345  0.17954556 -0.48279056  0.          0.        ]
 [ 0.81034483  0.17954556 -0.48279056  0.          0.        ]
 [ 0.82758621  0.17954556 -0.48279056  0.          0.        ]
 [ 0.84482759  0.17954556 -0.48279056  0.          0.        ]
 [ 0.86206897  0.17954556 -0.48279056  0.          0.        ]
 [ 0.87931034  0.17954556 -0.48279056  0.1610667   0.        ]
 [ 0.89655172  0.17954556 -0.48279056  0.17492377  0.        ]
 [ 0.9137931   0.17954556 -0.48279056  0.23057109  0.        ]
 [ 0.93103448  0.17954556 -0.48

[0.00305111 0.00225661]
[[ 0.79310345  0.17954556 -0.48279056  0.          0.        ]
 [ 0.81034483  0.17954556 -0.48279056  0.          0.        ]
 [ 0.82758621  0.17954556 -0.48279056  0.          0.        ]
 [ 0.84482759  0.17954556 -0.48279056  0.          0.        ]
 [ 0.86206897  0.17954556 -0.48279056  0.          0.        ]
 [ 0.87931034  0.17954556 -0.48279056  0.1610667   0.        ]
 [ 0.89655172  0.17954556 -0.48279056  0.17492377  0.        ]
 [ 0.9137931   0.17954556 -0.48279056  0.23057109  0.        ]
 [ 0.93103448  0.17954556 -0.48279056  0.30574396  0.        ]
 [ 0.94827586  0.17954556 -0.48279056  0.33160457  0.        ]
 [ 0.96551724  0.17954556 -0.48279056  0.34610146  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.39278293  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.00307284  0.00227016]
 [ 0.98275862  0.17954556 -0.48279056  0.00306128  0.00226741]
 [ 0.98275862  0.17954556 -0.48279056  0.00305924  0.00226543]
 [ 0.98275862  0.17954556 -0.48

[0.00305145 0.00225623]
[[ 0.87931034  0.17954556 -0.48279056  0.1610667   0.        ]
 [ 0.89655172  0.17954556 -0.48279056  0.17492377  0.        ]
 [ 0.9137931   0.17954556 -0.48279056  0.23057109  0.        ]
 [ 0.93103448  0.17954556 -0.48279056  0.30574396  0.        ]
 [ 0.94827586  0.17954556 -0.48279056  0.33160457  0.        ]
 [ 0.96551724  0.17954556 -0.48279056  0.34610146  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.39278293  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.00307284  0.00227016]
 [ 0.98275862  0.17954556 -0.48279056  0.00306128  0.00226741]
 [ 0.98275862  0.17954556 -0.48279056  0.00305924  0.00226543]
 [ 0.98275862  0.17954556 -0.48279056  0.0030582   0.00226401]
 [ 0.98275862  0.17954556 -0.48279056  0.00305733  0.00226281]
 [ 0.98275862  0.17954556 -0.48279056  0.00305647  0.00226174]
 [ 0.98275862  0.17954556 -0.48279056  0.00305566  0.00226082]
 [ 0.98275862  0.17954556 -0.48279056  0.00305491  0.00226002]
 [ 0.98275862  0.17954556 -0.48

[0.00304992 0.00225495]
[[ 0.96551724  0.17954556 -0.48279056  0.34610146  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.39278293  0.        ]
 [ 0.98275862  0.17954556 -0.48279056  0.00307284  0.00227016]
 [ 0.98275862  0.17954556 -0.48279056  0.00306128  0.00226741]
 [ 0.98275862  0.17954556 -0.48279056  0.00305924  0.00226543]
 [ 0.98275862  0.17954556 -0.48279056  0.0030582   0.00226401]
 [ 0.98275862  0.17954556 -0.48279056  0.00305733  0.00226281]
 [ 0.98275862  0.17954556 -0.48279056  0.00305647  0.00226174]
 [ 0.98275862  0.17954556 -0.48279056  0.00305566  0.00226082]
 [ 0.98275862  0.17954556 -0.48279056  0.00305491  0.00226002]
 [ 0.98275862  0.17954556 -0.48279056  0.00305424  0.00225933]
 [ 0.98275862  0.17954556 -0.48279056  0.00305362  0.00225875]
 [ 0.98275862  0.17954556 -0.48279056  0.00305308  0.00225825]
 [ 0.98275862  0.17954556 -0.48279056  0.00305261  0.00225784]
 [ 0.98275862  0.17954556 -0.48279056  0.0030522   0.0022575 ]
 [ 0.98275862  0.17954556 -0.48

[0.00304865 0.00225387]
[[ 0.98275862  0.17954556 -0.48279056  0.0030582   0.00226401]
 [ 0.98275862  0.17954556 -0.48279056  0.00305733  0.00226281]
 [ 0.98275862  0.17954556 -0.48279056  0.00305647  0.00226174]
 [ 0.98275862  0.17954556 -0.48279056  0.00305566  0.00226082]
 [ 0.98275862  0.17954556 -0.48279056  0.00305491  0.00226002]
 [ 0.98275862  0.17954556 -0.48279056  0.00305424  0.00225933]
 [ 0.98275862  0.17954556 -0.48279056  0.00305362  0.00225875]
 [ 0.98275862  0.17954556 -0.48279056  0.00305308  0.00225825]
 [ 0.98275862  0.17954556 -0.48279056  0.00305261  0.00225784]
 [ 0.98275862  0.17954556 -0.48279056  0.0030522   0.0022575 ]
 [ 0.98275862  0.17954556 -0.48279056  0.00305185  0.00225723]
 [ 0.98275862  0.17954556 -0.48279056  0.00305156  0.00225701]
 [ 0.98275862  0.17954556 -0.48279056  0.00305134  0.00225684]
 [ 0.98275862  0.17954556 -0.48279056  0.00305119  0.00225672]
 [ 0.98275862  0.17954556 -0.48279056  0.00305111  0.00225661]
 [ 0.98275862  0.17954556 -0.48

[0.0030659  0.00227265]
[[ 0.53448276  0.34094833 -0.84669111  0.          0.        ]
 [ 0.55172414  0.34094833 -0.84669111  0.          0.        ]
 [ 0.56896552  0.34094833 -0.84669111  0.          0.        ]
 [ 0.5862069   0.34094833 -0.84669111  0.          0.        ]
 [ 0.60344828  0.34094833 -0.84669111  0.          0.        ]
 [ 0.62068966  0.34094833 -0.84669111  0.          0.        ]
 [ 0.63793103  0.34094833 -0.84669111  0.          0.        ]
 [ 0.65517241  0.34094833 -0.84669111  0.          0.        ]
 [ 0.67241379  0.34094833 -0.84669111  0.          0.        ]
 [ 0.68965517  0.34094833 -0.84669111  0.          0.        ]
 [ 0.70689655  0.34094833 -0.84669111  0.          0.        ]
 [ 0.72413793  0.34094833 -0.84669111  0.          0.        ]
 [ 0.74137931  0.34094833 -0.84669111  0.          0.        ]
 [ 0.75862069  0.34094833 -0.84669111  0.          0.        ]
 [ 0.77586207  0.34094833 -0.84669111  0.          0.        ]
 [ 0.79310345  0.34094833 -0.84

[0.00306123 0.00226641]
[[ 0.63793103  0.34094833 -0.84669111  0.          0.        ]
 [ 0.65517241  0.34094833 -0.84669111  0.          0.        ]
 [ 0.67241379  0.34094833 -0.84669111  0.          0.        ]
 [ 0.68965517  0.34094833 -0.84669111  0.          0.        ]
 [ 0.70689655  0.34094833 -0.84669111  0.          0.        ]
 [ 0.72413793  0.34094833 -0.84669111  0.          0.        ]
 [ 0.74137931  0.34094833 -0.84669111  0.          0.        ]
 [ 0.75862069  0.34094833 -0.84669111  0.          0.        ]
 [ 0.77586207  0.34094833 -0.84669111  0.          0.        ]
 [ 0.79310345  0.34094833 -0.84669111  0.          0.        ]
 [ 0.81034483  0.34094833 -0.84669111  0.          0.        ]
 [ 0.82758621  0.34094833 -0.84669111  0.          0.        ]
 [ 0.84482759  0.34094833 -0.84669111  0.          0.        ]
 [ 0.86206897  0.34094833 -0.84669111  0.          0.        ]
 [ 0.87931034  0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.89655172  0.34094833 -0.84

[0.00305852 0.0022633 ]
[[ 0.75862069  0.34094833 -0.84669111  0.          0.        ]
 [ 0.77586207  0.34094833 -0.84669111  0.          0.        ]
 [ 0.79310345  0.34094833 -0.84669111  0.          0.        ]
 [ 0.81034483  0.34094833 -0.84669111  0.          0.        ]
 [ 0.82758621  0.34094833 -0.84669111  0.          0.        ]
 [ 0.84482759  0.34094833 -0.84669111  0.          0.        ]
 [ 0.86206897  0.34094833 -0.84669111  0.          0.        ]
 [ 0.87931034  0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.89655172  0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.9137931   0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.93103448  0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.94827586  0.34094833 -0.84669111  0.12461821  0.        ]
 [ 0.96551724  0.34094833 -0.84669111  0.17492377  0.        ]
 [ 0.98275862  0.34094833 -0.84669111  0.20698637  0.        ]
 [ 0.98275862  0.34094833 -0.84669111  0.00307371  0.00227652]
 [ 0.98275862  0.34094833 -0.84

[0.00305737 0.00226127]
[[ 0.93103448  0.34094833 -0.84669111  0.0623091   0.        ]
 [ 0.94827586  0.34094833 -0.84669111  0.12461821  0.        ]
 [ 0.96551724  0.34094833 -0.84669111  0.17492377  0.        ]
 [ 0.98275862  0.34094833 -0.84669111  0.20698637  0.        ]
 [ 0.98275862  0.34094833 -0.84669111  0.00307371  0.00227652]
 [ 0.98275862  0.34094833 -0.84669111  0.0030674   0.00227437]
 [ 0.98275862  0.34094833 -0.84669111  0.0030659   0.00227265]
 [ 0.98275862  0.34094833 -0.84669111  0.00306491  0.00227125]
 [ 0.98275862  0.34094833 -0.84669111  0.00306406  0.00227003]
 [ 0.98275862  0.34094833 -0.84669111  0.00306325  0.00226895]
 [ 0.98275862  0.34094833 -0.84669111  0.00306251  0.00226799]
 [ 0.98275862  0.34094833 -0.84669111  0.00306184  0.00226715]
 [ 0.98275862  0.34094833 -0.84669111  0.00306123  0.00226641]
 [ 0.98275862  0.34094833 -0.84669111  0.00306069  0.00226576]
 [ 0.98275862  0.34094833 -0.84669111  0.00306021  0.00226519]
 [ 0.98275862  0.34094833 -0.84

[0.00305644 0.00226038]
[[ 0.98275862  0.34094833 -0.84669111  0.00306406  0.00227003]
 [ 0.98275862  0.34094833 -0.84669111  0.00306325  0.00226895]
 [ 0.98275862  0.34094833 -0.84669111  0.00306251  0.00226799]
 [ 0.98275862  0.34094833 -0.84669111  0.00306184  0.00226715]
 [ 0.98275862  0.34094833 -0.84669111  0.00306123  0.00226641]
 [ 0.98275862  0.34094833 -0.84669111  0.00306069  0.00226576]
 [ 0.98275862  0.34094833 -0.84669111  0.00306021  0.00226519]
 [ 0.98275862  0.34094833 -0.84669111  0.00305978  0.0022647 ]
 [ 0.98275862  0.34094833 -0.84669111  0.0030594   0.00226428]
 [ 0.98275862  0.34094833 -0.84669111  0.00305906  0.00226391]
 [ 0.98275862  0.34094833 -0.84669111  0.00305877  0.00226358]
 [ 0.98275862  0.34094833 -0.84669111  0.00305852  0.0022633 ]
 [ 0.98275862  0.34094833 -0.84669111  0.00305831  0.00226305]
 [ 0.98275862  0.34094833 -0.84669111  0.00305814  0.00226282]
 [ 0.98275862  0.34094833 -0.84669111  0.003058    0.00226261]
 [ 0.98275862  0.34094833 -0.84

[0.00306416 0.00227206]
[[ 0.5862069   0.29962944 -0.64764722  0.          0.        ]
 [ 0.60344828  0.29962944 -0.64764722  0.          0.        ]
 [ 0.62068966  0.29962944 -0.64764722  0.          0.        ]
 [ 0.63793103  0.29962944 -0.64764722  0.          0.        ]
 [ 0.65517241  0.29962944 -0.64764722  0.          0.        ]
 [ 0.67241379  0.29962944 -0.64764722  0.          0.        ]
 [ 0.68965517  0.29962944 -0.64764722  0.          0.        ]
 [ 0.70689655  0.29962944 -0.64764722  0.          0.        ]
 [ 0.72413793  0.29962944 -0.64764722  0.          0.        ]
 [ 0.74137931  0.29962944 -0.64764722  0.          0.        ]
 [ 0.75862069  0.29962944 -0.64764722  0.0623091   0.        ]
 [ 0.77586207  0.29962944 -0.64764722  0.09875759  0.        ]
 [ 0.79310345  0.29962944 -0.64764722  0.14467726  0.        ]
 [ 0.81034483  0.29962944 -0.64764722  0.18692731  0.        ]
 [ 0.82758621  0.29962944 -0.64764722  0.18692731  0.        ]
 [ 0.84482759  0.29962944 -0.64

 [ 0.98275862  0.29962944 -0.64764722  0.00305686  0.00226839]]
[0.00305697 0.00226783]
[[ 0.77586207  0.29962944 -0.64764722  0.09875759  0.        ]
 [ 0.79310345  0.29962944 -0.64764722  0.14467726  0.        ]
 [ 0.81034483  0.29962944 -0.64764722  0.18692731  0.        ]
 [ 0.82758621  0.29962944 -0.64764722  0.18692731  0.        ]
 [ 0.84482759  0.29962944 -0.64764722  0.26929547  0.        ]
 [ 0.86206897  0.29962944 -0.64764722  0.26929547  0.        ]
 [ 0.87931034  0.29962944 -0.64764722  0.30574396  0.        ]
 [ 0.89655172  0.29962944 -0.64764722  0.30574396  0.        ]
 [ 0.9137931   0.29962944 -0.64764722  0.33160457  0.        ]
 [ 0.93103448  0.29962944 -0.64764722  0.36344215  0.        ]
 [ 0.94827586  0.29962944 -0.64764722  0.38811212  0.        ]
 [ 0.96551724  0.29962944 -0.64764722  0.41215665  0.        ]
 [ 0.98275862  0.29962944 -0.64764722  0.43036217  0.        ]
 [ 0.98275862  0.29962944 -0.64764722  0.00308823  0.00228533]
 [ 0.98275862  0.29962944 -0.6

 [ 0.98275862  0.29962944 -0.64764722  0.00305602  0.00226325]]
[0.00305558 0.00226217]
[[ 0.86206897  0.29962944 -0.64764722  0.26929547  0.        ]
 [ 0.87931034  0.29962944 -0.64764722  0.30574396  0.        ]
 [ 0.89655172  0.29962944 -0.64764722  0.30574396  0.        ]
 [ 0.9137931   0.29962944 -0.64764722  0.33160457  0.        ]
 [ 0.93103448  0.29962944 -0.64764722  0.36344215  0.        ]
 [ 0.94827586  0.29962944 -0.64764722  0.38811212  0.        ]
 [ 0.96551724  0.29962944 -0.64764722  0.41215665  0.        ]
 [ 0.98275862  0.29962944 -0.64764722  0.43036217  0.        ]
 [ 0.98275862  0.29962944 -0.64764722  0.00308823  0.00228533]
 [ 0.98275862  0.29962944 -0.64764722  0.00307442  0.00228124]
 [ 0.98275862  0.29962944 -0.64764722  0.00307062  0.00227802]
 [ 0.98275862  0.29962944 -0.64764722  0.00306812  0.00227561]
 [ 0.98275862  0.29962944 -0.64764722  0.00306602  0.00227365]
 [ 0.98275862  0.29962944 -0.64764722  0.00306416  0.00227206]
 [ 0.98275862  0.29962944 -0.6

[0.00305057 0.00225665]
[[ 0.98275862  0.29962944 -0.64764722  0.00308823  0.00228533]
 [ 0.98275862  0.29962944 -0.64764722  0.00307442  0.00228124]
 [ 0.98275862  0.29962944 -0.64764722  0.00307062  0.00227802]
 [ 0.98275862  0.29962944 -0.64764722  0.00306812  0.00227561]
 [ 0.98275862  0.29962944 -0.64764722  0.00306602  0.00227365]
 [ 0.98275862  0.29962944 -0.64764722  0.00306416  0.00227206]
 [ 0.98275862  0.29962944 -0.64764722  0.00306252  0.00227081]
 [ 0.98275862  0.29962944 -0.64764722  0.0030611   0.00226986]
 [ 0.98275862  0.29962944 -0.64764722  0.0030599   0.00226921]
 [ 0.98275862  0.29962944 -0.64764722  0.00305891  0.00226882]
 [ 0.98275862  0.29962944 -0.64764722  0.00305811  0.00226867]
 [ 0.98275862  0.29962944 -0.64764722  0.00305752  0.00226868]
 [ 0.98275862  0.29962944 -0.64764722  0.00305712  0.00226878]
 [ 0.98275862  0.29962944 -0.64764722  0.0030569   0.00226883]
 [ 0.98275862  0.29962944 -0.64764722  0.00305683  0.00226872]
 [ 0.98275862  0.29962944 -0.64

[0.00305012 0.00225625]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
find the day in teacher
[0.6201463958452815 0.001488095238095238]
[[0.48275862 0.17680944 0.65125778 0.61978282 0.0014881 ]
 [0.5        0.17680944 0.65125778 0.61987385 0.0014881 ]
 [0.51724138 0.17680944 0.65125778 0.61996479 0.0014881 ]
 [0.53448276 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.55172414 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.56896552 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.5862069  0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.60344828 0.17680944 0.65125778 0.62005

[0.8683268  0.53074896]
[[0.56896552 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.5862069  0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.60344828 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.62068966 0.17680944 0.65125778 0.62005564 0.0014881 ]
 [0.63793103 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.65517241 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.67241379 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.68965517 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.70689655 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.72413793 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.74137931 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.75862069 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.77586207 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.79310345 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.81034483 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.82758621 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.84482759 0.17680944 0.65125778 0.6201464  0.

 [0.98275862 0.17680944 0.65125778 0.94558877 0.62950927]]
[0.9521319 0.6427203]
[[0.67241379 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.68965517 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.70689655 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.72413793 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.74137931 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.75862069 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.77586207 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.79310345 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.81034483 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.82758621 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.84482759 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.86206897 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.87931034 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.89655172 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.9137931  0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.93103448 0.17680944 0.65125778 0.6201464  0.0

 [0.98275862 0.17680944 0.65125778 0.96914411 0.69611967]]
[0.96970236 0.69886386]
[[0.82758621 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.84482759 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.86206897 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.87931034 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.89655172 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.9137931  0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.93103448 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.94827586 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.96551724 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.98275862 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.98275862 0.17680944 0.65125778 0.83256322 0.51698673]
 [0.98275862 0.17680944 0.65125778 0.82854491 0.50565046]
 [0.98275862 0.17680944 0.65125778 0.83452463 0.50480396]
 [0.98275862 0.17680944 0.65125778 0.84879905 0.51390409]
 [0.98275862 0.17680944 0.65125778 0.86832678 0.53074896]
 [0.98275862 0.17680944 0.65125778 0.88931471 0

[0.9716247 0.7088505]
[[0.98275862 0.17680944 0.65125778 0.6201464  0.0014881 ]
 [0.98275862 0.17680944 0.65125778 0.83256322 0.51698673]
 [0.98275862 0.17680944 0.65125778 0.82854491 0.50565046]
 [0.98275862 0.17680944 0.65125778 0.83452463 0.50480396]
 [0.98275862 0.17680944 0.65125778 0.84879905 0.51390409]
 [0.98275862 0.17680944 0.65125778 0.86832678 0.53074896]
 [0.98275862 0.17680944 0.65125778 0.88931471 0.55207443]
 [0.98275862 0.17680944 0.65125778 0.90858388 0.57449299]
 [0.98275862 0.17680944 0.65125778 0.92443764 0.59548551]
 [0.98275862 0.17680944 0.65125778 0.93660069 0.61387056]
 [0.98275862 0.17680944 0.65125778 0.94558877 0.62950927]
 [0.98275862 0.17680944 0.65125778 0.95213193 0.64272028]
 [0.98275862 0.17680944 0.65125778 0.95689219 0.65390396]
 [0.98275862 0.17680944 0.65125778 0.96038133 0.66339272]
 [0.98275862 0.17680944 0.65125778 0.96296912 0.67144144]
 [0.98275862 0.17680944 0.65125778 0.96491539 0.67824996]
 [0.98275862 0.17680944 0.65125778 0.96639943 0.68

[0.00306912 0.00227213]
[[ 0.51724138  0.18738778 -0.61906222  0.          0.        ]
 [ 0.53448276  0.18738778 -0.61906222  0.          0.        ]
 [ 0.55172414  0.18738778 -0.61906222  0.          0.        ]
 [ 0.56896552  0.18738778 -0.61906222  0.          0.        ]
 [ 0.5862069   0.18738778 -0.61906222  0.          0.        ]
 [ 0.60344828  0.18738778 -0.61906222  0.          0.        ]
 [ 0.62068966  0.18738778 -0.61906222  0.          0.        ]
 [ 0.63793103  0.18738778 -0.61906222  0.          0.        ]
 [ 0.65517241  0.18738778 -0.61906222  0.          0.        ]
 [ 0.67241379  0.18738778 -0.61906222  0.          0.        ]
 [ 0.68965517  0.18738778 -0.61906222  0.          0.        ]
 [ 0.70689655  0.18738778 -0.61906222  0.          0.        ]
 [ 0.72413793  0.18738778 -0.61906222  0.          0.        ]
 [ 0.74137931  0.18738778 -0.61906222  0.          0.        ]
 [ 0.75862069  0.18738778 -0.61906222  0.          0.        ]
 [ 0.77586207  0.18738778 -0.61

[0.00305962 0.00226294]
[[ 0.63793103  0.18738778 -0.61906222  0.          0.        ]
 [ 0.65517241  0.18738778 -0.61906222  0.          0.        ]
 [ 0.67241379  0.18738778 -0.61906222  0.          0.        ]
 [ 0.68965517  0.18738778 -0.61906222  0.          0.        ]
 [ 0.70689655  0.18738778 -0.61906222  0.          0.        ]
 [ 0.72413793  0.18738778 -0.61906222  0.          0.        ]
 [ 0.74137931  0.18738778 -0.61906222  0.          0.        ]
 [ 0.75862069  0.18738778 -0.61906222  0.          0.        ]
 [ 0.77586207  0.18738778 -0.61906222  0.          0.        ]
 [ 0.79310345  0.18738778 -0.61906222  0.          0.        ]
 [ 0.81034483  0.18738778 -0.61906222  0.          0.        ]
 [ 0.82758621  0.18738778 -0.61906222  0.17492377  0.        ]
 [ 0.84482759  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.86206897  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.87931034  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.89655172  0.18738778 -0.61

[0.00305646 0.0022606 ]
[[ 0.75862069  0.18738778 -0.61906222  0.          0.        ]
 [ 0.77586207  0.18738778 -0.61906222  0.          0.        ]
 [ 0.79310345  0.18738778 -0.61906222  0.          0.        ]
 [ 0.81034483  0.18738778 -0.61906222  0.          0.        ]
 [ 0.82758621  0.18738778 -0.61906222  0.17492377  0.        ]
 [ 0.84482759  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.86206897  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.87931034  0.18738778 -0.61906222  0.20698637  0.        ]
 [ 0.89655172  0.18738778 -0.61906222  0.23057109  0.        ]
 [ 0.9137931   0.18738778 -0.61906222  0.23723288  0.        ]
 [ 0.93103448  0.18738778 -0.61906222  0.26468456  0.        ]
 [ 0.94827586  0.18738778 -0.61906222  0.27368137  0.        ]
 [ 0.96551724  0.18738778 -0.61906222  0.29954198  0.        ]
 [ 0.98275862  0.18738778 -0.61906222  0.3441682   0.        ]
 [ 0.98275862  0.18738778 -0.61906222  0.0030797   0.00227502]
 [ 0.98275862  0.18738778 -0.61

[0.00305438 0.00225749]
[[ 0.93103448  0.18738778 -0.61906222  0.26468456  0.        ]
 [ 0.94827586  0.18738778 -0.61906222  0.27368137  0.        ]
 [ 0.96551724  0.18738778 -0.61906222  0.29954198  0.        ]
 [ 0.98275862  0.18738778 -0.61906222  0.3441682   0.        ]
 [ 0.98275862  0.18738778 -0.61906222  0.0030797   0.00227502]
 [ 0.98275862  0.18738778 -0.61906222  0.00306912  0.00227213]
 [ 0.98275862  0.18738778 -0.61906222  0.00306667  0.00226991]
 [ 0.98275862  0.18738778 -0.61906222  0.00306514  0.00226823]
 [ 0.98275862  0.18738778 -0.61906222  0.00306383  0.00226681]
 [ 0.98275862  0.18738778 -0.61906222  0.00306261  0.00226559]
 [ 0.98275862  0.18738778 -0.61906222  0.00306149  0.00226455]
 [ 0.98275862  0.18738778 -0.61906222  0.0030605   0.00226367]
 [ 0.98275862  0.18738778 -0.61906222  0.00305962  0.00226294]
 [ 0.98275862  0.18738778 -0.61906222  0.00305885  0.00226234]
 [ 0.98275862  0.18738778 -0.61906222  0.00305819  0.00226186]
 [ 0.98275862  0.18738778 -0.61

[0.0030524  0.00225589]
[[ 0.98275862  0.18738778 -0.61906222  0.00306667  0.00226991]
 [ 0.98275862  0.18738778 -0.61906222  0.00306514  0.00226823]
 [ 0.98275862  0.18738778 -0.61906222  0.00306383  0.00226681]
 [ 0.98275862  0.18738778 -0.61906222  0.00306261  0.00226559]
 [ 0.98275862  0.18738778 -0.61906222  0.00306149  0.00226455]
 [ 0.98275862  0.18738778 -0.61906222  0.0030605   0.00226367]
 [ 0.98275862  0.18738778 -0.61906222  0.00305962  0.00226294]
 [ 0.98275862  0.18738778 -0.61906222  0.00305885  0.00226234]
 [ 0.98275862  0.18738778 -0.61906222  0.00305819  0.00226186]
 [ 0.98275862  0.18738778 -0.61906222  0.00305764  0.00226147]
 [ 0.98275862  0.18738778 -0.61906222  0.0030572   0.00226117]
 [ 0.98275862  0.18738778 -0.61906222  0.00305686  0.00226094]
 [ 0.98275862  0.18738778 -0.61906222  0.00305661  0.00226075]
 [ 0.98275862  0.18738778 -0.61906222  0.00305646  0.0022606 ]
 [ 0.98275862  0.18738778 -0.61906222  0.00305638  0.00226045]
 [ 0.98275862  0.18738778 -0.61

KeyboardInterrupt: 

In [27]:
train_df_on_idx = train_df[(all_df["Country/Region"] == idx[1]) &
                           (all_df["Province/State"] == idx[0])]

In [69]:
train_df_on_idx = train_df[(all_df["Country/Region"] == idx[1]) &
                           (all_df["Province/State"] == idx[0])]
print(train_df_on_idx["Date"].values)
int(1000000000*(datetime.timedelta(days=day) + test_df_on_idx["Date"].min()).timestamp()) in train_df_on_idx["Date"].values

['2020-01-22T00:00:00.000000000' '2020-01-23T00:00:00.000000000'
 '2020-01-24T00:00:00.000000000' '2020-01-25T00:00:00.000000000'
 '2020-01-26T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-01-28T00:00:00.000000000' '2020-01-29T00:00:00.000000000'
 '2020-01-30T00:00:00.000000000' '2020-01-31T00:00:00.000000000'
 '2020-02-01T00:00:00.000000000' '2020-02-02T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-04T00:00:00.000000000'
 '2020-02-05T00:00:00.000000000' '2020-02-06T00:00:00.000000000'
 '2020-02-07T00:00:00.000000000' '2020-02-08T00:00:00.000000000'
 '2020-02-09T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-11T00:00:00.000000000' '2020-02-12T00:00:00.000000000'
 '2020-02-13T00:00:00.000000000' '2020-02-14T00:00:00.000000000'
 '2020-02-15T00:00:00.000000000' '2020-02-16T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-18T00:00:00.000000000'
 '2020-02-19T00:00:00.000000000' '2020-02-20T00:00:00.000000000'
 '2020-02-21T00:00:00.000

/Users/yamaguchir/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  after removing the cwd from sys.path.


False

In [72]:
test_df_on_idx.Date.min()

Timestamp('2020-03-12 00:00:00')

In [28]:
train_df_on_idx

Id Province/State Country/Region       Lat      Long       Date  \
2006  3163        Alberta         Canada  0.299629 -0.647647 2020-01-22   
2007  3164        Alberta         Canada  0.299629 -0.647647 2020-01-23   
2008  3165        Alberta         Canada  0.299629 -0.647647 2020-01-24   
2009  3166        Alberta         Canada  0.299629 -0.647647 2020-01-25   
2010  3167        Alberta         Canada  0.299629 -0.647647 2020-01-26   
2011  3168        Alberta         Canada  0.299629 -0.647647 2020-01-27   
2012  3169        Alberta         Canada  0.299629 -0.647647 2020-01-28   
2013  3170        Alberta         Canada  0.299629 -0.647647 2020-01-29   
2014  3171        Alberta         Canada  0.299629 -0.647647 2020-01-30   
2015  3172        Alberta         Canada  0.299629 -0.647647 2020-01-31   
2016  3173        Alberta         Canada  0.299629 -0.647647 2020-02-01   
2017  3174        Alberta         Canada  0.299629 -0.647647 2020-02-02   
2018  3175        Alberta         Canada  0.299629 -0.647647 2020-02-03   
2019  3176        Alberta         Canada  0.299629 -0.647647 2020-02-04   
2020  3177        Alberta         Canada  0.299629 -0.647647 2020-02-05   
2021  3178        Alberta         Canada  0.299629 -0.647647 2020-02-06   
2022  3179        Alberta         Canada  0.299629 -0.647647 2020-02-07   
2023  3180        Alberta         Canada  0.299629 -0.647647 2020-02-08   
2024  3181        Alberta         Canada  0.299629 -0.647647 2020-02-09   
2025  3182        Alberta         Canada  0.299629 -0.647647 2020-02-10   
2026  3183        Alberta         Canada  0.299629 -0.647647 2020-02-11   
2027  3184        Alberta         Canada  0.299629 -0.647647 2020-02-12   
2028  3185        Alberta         Canada  0.299629 -0.647647 2020-02-13   
2029  3186        Alberta         Canada  0.299629 -0.647647 2020-02-14   
2030  3187        Alberta         Canada  0.299629 -0.647647 2020-02-15   
2031  3188        Alberta         Canada  0.299629 -0.647647 2020-02-16   
2032  3189        Alberta         Canada  0.299629 -0.647647 2020-02-17   
2033  3190        Alberta         Canada  0.299629 -0.647647 2020-02-18   
2034  3191        Alberta         Canada  0.299629 -0.647647 2020-02-19   
2035  3192        Alberta         Canada  0.299629 -0.647647 2020-02-20   
2036  3193        Alberta         Canada  0.299629 -0.647647 2020-02-21   
2037  3194        Alberta         Canada  0.299629 -0.647647 2020-02-22   
2038  3195        Alberta         Canada  0.299629 -0.647647 2020-02-23   
2039  3196        Alberta         Canada  0.299629 -0.647647 2020-02-24   
2040  3197        Alberta         Canada  0.299629 -0.647647 2020-02-25   
2041  3198        Alberta         Canada  0.299629 -0.647647 2020-02-26   
2042  3199        Alberta         Canada  0.299629 -0.647647 2020-02-27   
2043  3200        Alberta         Canada  0.299629 -0.647647 2020-02-28   
2044  3201        Alberta         Canada  0.299629 -0.647647 2020-02-29   
2045  3202        Alberta         Canada  0.299629 -0.647647 2020-03-01   
2046  3203        Alberta         Canada  0.299629 -0.647647 2020-03-02   
2047  3204        Alberta         Canada  0.299629 -0.647647 2020-03-03   
2048  3205        Alberta         Canada  0.299629 -0.647647 2020-03-04   
2049  3206        Alberta         Canada  0.299629 -0.647647 2020-03-05   
2050  3207        Alberta         Canada  0.299629 -0.647647 2020-03-06   
2051  3208        Alberta         Canada  0.299629 -0.647647 2020-03-07   
2052  3209        Alberta         Canada  0.299629 -0.647647 2020-03-08   
2053  3210        Alberta         Canada  0.299629 -0.647647 2020-03-09   
2054  3211        Alberta         Canada  0.299629 -0.647647 2020-03-10   
2055  3212        Alberta         Canada  0.299629 -0.647647 2020-03-11   
2056  3213        Alberta         Canada  0.299629 -0.647647 2020-03-12   
2057  3214        Alberta         Canada  0.299629 -0.647647 2020-03-13   
2058  3215        Alberta        

In [24]:

all_df = train_df.fillna({"Province/State": "NAN"})

In [45]:
int((datetime.timedelta(days=1) + test_df_on_idx["Date"].min()).timestamp()) in train_df_on_idx.Date.values.tolist()

False

In [64]:
int(1000000000*(datetime.timedelta(days=1) + test_df_on_idx["Date"].min()).timestamp()) in train_df_on_idx.Date.values.tolist()

True

In [48]:
train_df_on_idx.Date.values.tolist()[0]

1579651200000000000

In [38]:
(datetime.timedelta(days=1) + test_df_on_idx["Date"].min()).values

AttributeError: 'Timestamp' object has no attribute 'values'

In [41]:
test_df_on_idx["Date"].values

array(['2020-03-12T00:00:00.000000000', '2020-03-13T00:00:00.000000000',
       '2020-03-14T00:00:00.000000000', '2020-03-15T00:00:00.000000000',
       '2020-03-16T00:00:00.000000000', '2020-03-17T00:00:00.000000000',
       '2020-03-18T00:00:00.000000000', '2020-03-19T00:00:00.000000000',
       '2020-03-20T00:00:00.000000000', '2020-03-21T00:00:00.000000000',
       '2020-03-22T00:00:00.000000000', '2020-03-23T00:00:00.000000000',
       '2020-03-24T00:00:00.000000000', '2020-03-25T00:00:00.000000000',
       '2020-03-26T00:00:00.000000000', '2020-03-27T00:00:00.000000000',
       '2020-03-28T00:00:00.000000000', '2020-03-29T00:00:00.000000000',
       '2020-03-30T00:00:00.000000000', '2020-03-31T00:00:00.000000000',
       '2020-04-01T00:00:00.000000000', '2020-04-02T00:00:00.000000000',
       '2020-04-03T00:00:00.000000000', '2020-04-04T00:00:00.000000000',
       '2020-04-05T00:00:00.000000000', '2020-04-06T00:00:00.000000000',
       '2020-04-07T00:00:00.000000000', '2020-04-08

In [35]:
train_df_on_idx.Date.values

array(['2020-01-22T00:00:00.000000000', '2020-01-23T00:00:00.000000000',
       '2020-01-24T00:00:00.000000000', '2020-01-25T00:00:00.000000000',
       '2020-01-26T00:00:00.000000000', '2020-01-27T00:00:00.000000000',
       '2020-01-28T00:00:00.000000000', '2020-01-29T00:00:00.000000000',
       '2020-01-30T00:00:00.000000000', '2020-01-31T00:00:00.000000000',
       '2020-02-01T00:00:00.000000000', '2020-02-02T00:00:00.000000000',
       '2020-02-03T00:00:00.000000000', '2020-02-04T00:00:00.000000000',
       '2020-02-05T00:00:00.000000000', '2020-02-06T00:00:00.000000000',
       '2020-02-07T00:00:00.000000000', '2020-02-08T00:00:00.000000000',
       '2020-02-09T00:00:00.000000000', '2020-02-10T00:00:00.000000000',
       '2020-02-11T00:00:00.000000000', '2020-02-12T00:00:00.000000000',
       '2020-02-13T00:00:00.000000000', '2020-02-14T00:00:00.000000000',
       '2020-02-15T00:00:00.000000000', '2020-02-16T00:00:00.000000000',
       '2020-02-17T00:00:00.000000000', '2020-02-18

In [32]:
test_df_on_idx["Date"].min()

Timestamp('2020-03-12 00:00:00')

In [ ]:
submit_df = pd.read_csv(data_dir+"submission.csv", index_col=0)

In [ ]:
submit_df

In [ ]:
cases = []
fatals = []
for i in range(len(results)):
    n = results[i][0] 
    f = results[i][1]
    try:
        cases.append(int(n))
    except:
        cases.append(0)
    
    try:
        fatals.append(int(f))
    except:
        fatals.append(0)

In [ ]:
submit_df["ConfirmedCases"] = cases
submit_df["Fatalities"] = fatals

In [ ]:
submit_df.to_csv("submission.csv")